name: Second Workflow
on: 
  push:
  workflow_dispatch:
jobs: 
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Welcome"
        run: echo "Welcome to the second workflow!"
  bye-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Goodbye"
        run: echo "Goodbye from the second workflow!"
